added new logging step

diff --git a/.github/workflows/golang_test.yml b/.github/workflows/golang_test.yml
--- a/.github/workflows/golang_test.yml
+++ b/.github/workflows/golang_test.yml
@@ -16,31 +16,40 @@ jobs:
     test:
         name: Testing golang backend
         runs-on: ubuntu-latest
+        env:
+          ENV: continuous_integration
         steps:
-            - name: Check out code
-              uses: actions/checkout@v4
+          - name: Check out code
+            uses: actions/checkout@v4
 
-            - name: Set up Go
-              uses: actions/setup-go@v4
-              with:
-                  go-version: 1.22.2
+          - name: Set up Go
+            uses: actions/setup-go@v4
+            with:
+                go-version: 1.22.2
 
-            - name: Install Docker
-              run: |
-                sudo apt-get update
-                sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
-                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
-                echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
-                sudo apt-get update
-                sudo apt-get install -y docker-ce docker-ce-cli containerd.io
-                sudo systemctl start docker
-                sudo systemctl enable docker
-                docker --version
+          - name: Log environment variables and exit
+            run: |
+              echo "Logging environment variables..."
+              env
+              echo "$ENV"
+              exit 0  # Exit successfully (change to `exit 1` if you want to fail the job)
 
-            - name: Install dependencies
-              run: go mod download
-              working-directory: server-golang
+          - name: Install Docker
+            run: |
+              sudo apt-get update
+              sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
+              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+              echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+              sudo apt-get update
+              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
+              sudo systemctl start docker
+              sudo systemctl enable docker
+              docker --version
 
-            - name: Run tests
-              run: go test -v ./...
-              working-directory: server-golang
+          - name: Install dependencies
+            run: go mod download
+            working-directory: server-golang
+
+          - name: Run tests
+            run: go test -v ./...
+            working-directory: server-golang
